### ISSUE TITLE
Updating codebase to match schema

### ISSUE THREAD

**Issue by isuftin** [rickatnight11/docker_musicbrainz#4]
I was working on creating the Musicbrainz database container last night and was attempting to restore the latest dumps from the musicbrainz mirror.

The result was:

```
musicbrainzDb_1 | Mon Aug  3 00:29:50 2015 : Pre-checking /dump/mbdump-cdstubs.tar.bz2
musicbrainzDb_1 | Mon Aug  3 00:29:50 2015 : Schema sequence mismatch - codebase is 21, /dump/mbdump-cdstubs.tar.bz2 is 22
musicbrainzDb_1 |
musicbrainzDb_1 | Failed to import dataset.
musicbrainzDb_1 | Mon Aug  3 00:29:50 2015 : InitDb.pl failed
```

This is due to their datasets being at a version ahead of their codebase currently on github.

I went to their IRC chan on Freenode and they suggest following this: http://blog.musicbrainz.org/2015/05/19/schema-change-release-2015-05-18-including-upgrade-instructions/

They're suggesting that this is a constant issue when they do merges about every 6 months. 

I'm wondering if you have any thoughts on how this can be made maintainable in Docker images. I have a few thoughts but nothing solid as of yet.

**Comment by rickatnight11** [comment]
Ahah, this is because you're using an older DBDefs.pm.  The one in the repo (which I mostly left there so the Docker builders would work) just needs `DB_SCHEMA_SEQUENCE` changed from `21` to `22`, but honestly you should be customizing that anyway.

This repo is currently building against the `v-2015-07-13` tag of MusicBrainz, so you can just grab the sample `DBDefs.pm` from https://github.com/metabrainz/musicbrainz-server/blob/v-2015-07-13/lib/DBDefs.pm.sample, modify it appropriately for your environment, and rebuild your `musicbrainz` container.  Let me know how it goes.

**Comment by rickatnight11** [comment]
I just pushed two changes to `DBDefs.pm` that bring it up to speed with the `v-2015-07-13` tag (updating the schema sequence and adding the replication token setting, which is now required for performing syncs).
